# Generated by Django 5.0 on 2025-11-30 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('url', models.URLField(unique=True)),
                ('pais', models.CharField(blank=True, max_length=100)),
                ('codigo_liga', models.CharField(blank=True, max_length=50)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Ligas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='ligas.liga')),
            ],
            options={
                'verbose_name_plural': 'Equipos',
                'ordering': ['nombre'],
                'unique_together': {('liga', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.IntegerField()),
                ('goles_local', models.IntegerField(blank=True, null=True)),
                ('goles_visitante', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_juego', 'En Juego'), ('finalizado', 'Finalizado'), ('suspendido', 'Suspendido')], default='programado', max_length=20)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='ligas.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='ligas.equipo')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='ligas.liga')),
            ],
            options={
                'verbose_name_plural': 'Partidos',
                'ordering': ['jornada', 'fecha', 'hora'],
                'unique_together': {('liga', 'jornada', 'equipo_local', 'equipo_visitante')},
            },
        ),
    ]
