# Generated by Django 5.0 on 2025-12-01 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liga',
            options={'ordering': ['continente', 'nombre'], 'verbose_name_plural': 'Ligas'},
        ),
        migrations.AddField(
            model_name='liga',
            name='continente',
            field=models.CharField(choices=[('europa', 'Europa'), ('america', 'América'), ('asia', 'Asia'), ('africa', 'África'), ('oceania', 'Oceanía')], default='europa', max_length=20),
        ),
    ]
