# Generated by Django 5.0 on 2025-12-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligas', '0002_alter_liga_options_liga_continente'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='pronostico_1x2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='pronostico_1x2_acertado',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
